INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Richard Shelby', 'Alabama', 'AL', 'Republican', 'N00009920', 1, 1986);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jeff  Sessions', 'Alabama', 'AL', 'Republican', 'N00003062', 1, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Lisa Murkowkski', 'Alaska', 'AK', 'Republican', 'N00026050', 2, 2002);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Dan Sullivan', 'Alaska', 'AK', 'Republican', 'N00035774', 2, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('John McCain', 'Arizona', 'AZ', 'Republican', 'N00006424', 4, 1986);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jeff Flake', 'Arizona', 'AZ', 'Republican', 'N00009573', 4, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('John Bozzman', 'Arkansas', 'AR', 'Republican', 'N00013873', 5, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Tom Cotton', 'Arkansas', 'AR', 'Republican', 'N00033363', 5, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Dianne Feinstein', 'California', 'CA', 'Democrat', 'N00007364', 6, 1992);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Barbara Boxer', 'California', 'CA', 'Democrat', 'N00006692', 6, 1992);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Michael Bennet', 'Colorado', 'CO', 'Democrat', 'N00030608', 8, 2009);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Cory Gardner', 'Colorado', 'CO', 'Republican', 'N00030780', 8, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Richard Blumenthal', 'Connecticut', 'CT', 'Democrat', 'N00031685', 9, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Chris Murphy', 'Connecticut', 'CT', 'Democrat', 'N00027566', 9, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Tom Carper', 'Delaware', 'DE', 'Democrat', 'N00012508', 10, 2000);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Chris Coons', 'Delaware', 'DE', 'Democrat', 'N00031820', 10, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Bill Nelson', 'Florida', 'FL', 'Democrat', 'N00009926', 12, 2000);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Marco Rubio', 'Florida', 'FL', 'Republican', 'N00030612', 12, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Johnny Isakson', 'Georgia', 'GA', 'Republican', 'N00002593', 13, 2004);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('David Perdue', 'Georgia', 'GA', 'Republican', 'N00035516', 13, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Brian Schatz', 'Hawaii', 'HI', 'Democrat', 'N00028138', 15, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mazie Hirono', 'Hawaii', 'HI', 'Democrat', 'N00028139', 15, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mike Crapo', 'Idaho', 'ID', 'Republican', 'N00006267', 16, 1998);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jim Risch', 'Idaho', 'ID', 'Republican', 'N00029441', 16, 2008);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Dick Durbin', 'Illinois', 'IL', 'Democrat', 'N00004981', 17, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mark Kirk', 'Illinois', 'IL', 'Republican', 'N00012539', 17, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Dan Coats', 'Indiana', 'IN', 'Republican', 'N00003845', 18, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Joe Donnelly', 'Indiana', 'IN', 'Democrat', 'N00026586', 18, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Chuck Grassley', 'Iowa', 'IA', 'Republican', 'N00001758', 19, 1980);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Joni Ernst', 'Iowa', 'IA', 'Republican', 'N00035483', 19, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Pat Roberts', 'Kansas', 'KS', 'Republican', 'N00005285', 20, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jerry Moran', 'Kansas', 'KS', 'Republican', 'N00005282', 20, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mitch McConnell', 'Kentucky', 'KY', 'Republican', 'N00003389', 21, 1984);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Rand Paul', 'Kentucky', 'KY', 'Republican', 'N00030836', 21, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('David Vitter', 'Louisiana', 'LA', 'Republican', 'N00009659', 22, 2004);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Bill Cassidy', 'Louisiana', 'LA', 'Republican', 'N00030245', 22, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Susan Collins', 'Maine', 'ME', 'Republican', 'N00000491', 23, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Angus King', 'Maine', 'ME', 'Independent', 'N00034580', 23, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Barbara Mikulski', 'Maryland', 'MD', 'Democrat', 'N00001945', 24, 1986);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Ben Cardin', 'Maryland', 'MD', 'Democrat', 'N00001955', 24, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Elizabeth Warren', 'Massachusetts', 'MA', 'Democrat', 'N00033492', 25, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Ed Markey', 'Massachusetts', 'MA', 'Democrat', 'N00000270', 25, 2013);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Debbie Stabenow', 'Michigan', 'MI', 'Democrat', 'N00004118', 26, 2000);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Gary Peters', 'Michigan', 'MI', 'Democrat', 'N00029277', 26, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Amy Klobuchar', 'Minnesota', 'MN', 'Democrat', 'N00027500', 27, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Al Fraken', 'Minnesota', 'MN', 'Democrat', 'N00029016', 27, 2008);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Thad Cochran', 'Mississippi', 'MS', 'Republican', 'N00003328', 28, 1978);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Roger Wicker', 'Mississippi', 'MS', 'Republican', 'N00003280', 28, 2007);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Claire McCaskill', 'Missouri', 'MO', 'Democrat', 'N00027694', 29, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Roy Blunt', 'Missouri', 'MO', 'Republican', 'N00005195', 29, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jon Tester', 'Montana', 'MT', 'Democrat', 'N00027605', 30, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Steve Daines', 'Montana', 'MT', 'Republican', 'N00033054', 30, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Deb Fischer', 'Nebraska', 'NE', 'Republican', 'N00033443', 31, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Ben Sasse', 'Nebraska', 'NE', 'Republican', 'N00035544', 31, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Harry Reid', 'Nevada', 'NV', 'Democrat', 'N00009922', 32, 1986);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Dean Heller', 'Nevada', 'NV', 'Republican', 'N00027522', 32, 2011);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jeanne Shaheen', 'New Hampshire', 'NH', 'Democrat', 'N00024790', 33, 2008);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Kelly Ayotte', 'New Hampshire', 'NH', 'Republican', 'N00030980', 33, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Bob Menedez', 'New Jersey', 'NJ', 'Democrat', 'N00000699', 34, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Cory Booker', 'New Jersey', 'NJ', 'Democrat', 'N00035267', 34, 2013);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Tom Udall', 'New Mexico', 'NM', 'Democrat', 'N00006561', 35, 2008);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Martin Heinrich', 'New Mexico', 'NM', 'Democrat', 'N00029835', 35, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Chuck Schumer', 'New York', 'NY', 'Democrat', 'N00001093', 36, 1998);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Kirsten Gillibrand', 'New York', 'NY', 'Democrat', 'N00027658', 36, 2009);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Richard Burr', 'North Carolina', 'NC', 'Republican', 'N00002221', 37, 2004);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Thom Tillis', 'North Carolina', 'NC', 'Republican', 'N00035492', 37, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('John Hoeven', 'North Dakota', 'ND', 'Republican', 'N00031688', 38, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Heidi Heitkamp', 'North Dakota', 'ND', 'Democrat', 'N00033782', 38, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Sherrod Brown', 'Ohio', 'OH', 'Democrat', 'N00003535', 39, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Rob Portman', 'Ohio', 'OH', 'Republican', 'N00003682', 39, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jim Inhofe', 'Oklahoma', 'OK', 'Republican', 'N00005582', 40, 2004);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('James Lankford', 'Oklahoma', 'OK', 'Republican', 'N00031129', 40, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Ron Wyden', 'Oregon', 'OR', 'Democrat', 'N00007724', 41, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jeff Merkley', 'Oregon', 'OR', 'Democrat', 'N00029303', 41, 2008);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Bob Casey Jr.', 'Pennsylvania', 'PA', 'Democrat', 'N00027503', 42, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Pat Toomey', 'Pennsylvania', 'PA', 'Republican', 'N00001489', 42, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Jack Reed', 'Rhode Island', 'RI', 'Democrat', 'N00000362', 44, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Sheldon Whitehouse', 'Rhode Island', 'RI', 'Democrat', 'N00027533', 44, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Lindsey Graham', 'South Carolina', 'SC', 'Republican', 'N00009975', 45, 2002);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Tim Scott', 'South Carolina', 'SC', 'Republican', 'N00031782', 45, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('John Thune', 'South Dakota', 'SD', 'Republican', 'N00004572', 46, 2004);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mike  Rounds', 'South Dakota', 'SD', 'Republican', 'N00035187', 46, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Lamar Alexander', 'Tennessee', 'TN', 'Republican', 'N00009888', 47, 2002);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Bob Corker', 'Tennessee', 'TN', 'Republican', 'N00027441', 47, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('John Cornyn', 'Texas', 'TX', 'Republican', 'N00024852', 48, 2002);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Ted Cruz', 'Texas', 'TX', 'Republican', 'N00033085', 48, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Orrin Hatch', 'Utah', 'UT', 'Republican', 'N00009869', 49, 1976);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mike Lee', 'Utah', 'UT', 'Republican', 'N00031696', 49, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Patrick Leahy', 'Vermont', 'VT', 'Democrat', 'N00009918', 50, 1974);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Bernie Sanders', 'Vermont', 'VT', 'Independent', 'N00000528', 50, 2006);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mark Warner', 'Virginia', 'VA', 'Democrat', 'N00002097', 51, 2008);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Tim Kaine', 'Virginia', 'VA', 'Democrat', 'N00033177', 51, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Patty Murray', 'Washington', 'WA', 'Democrat', 'N00007876', 53, 1992);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Maria Cantwell', 'Washington', 'WA', 'Democrat', 'N00007836', 53, 2000);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Joe Manchin', 'West Virginia', 'WV', 'Democrat', 'N00032838', 54, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Shelly Moore Capito', 'West Virginia', 'WV', 'Republican', 'N00009771', 54, 2014);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Ron Johnson', 'Wisconsin', 'WI', 'Republican', 'N00032546', 55, 2010);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Tammy Baldwin', 'Wisconsin', 'WI', 'Democrat', 'N00004367', 55, 2012);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('Mike Enzi', 'Wyoming', 'WY', 'Republican', 'N00006249', 56, 1996);
INSERT INTO senators (name, state, state_abr, party, api_id, geojson_id, year_elected) VALUES ('John Barrasso', 'Wyoming', 'WY', 'Republican', 'N00006236', 56, 2007);
