INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Richard Shelby', 'Alabama', 'Republican', 'N00009920', 1986);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jeff  Sessions', 'Alabama', 'Republican', 'N00003062', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Lisa Murkowkski', 'Alaska', 'Republican', 'N00026050', 2002);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Dan Sullivan', 'Alaska', 'Republican', 'N00035774', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('John McCain', 'Arizona', 'Republican', 'N00006424', 1986);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jeff Flake', 'Arizona', 'Republican', 'N00009573', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('John Bozzman', 'Arkansas', 'Republican', 'N00013873', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Tom Cotton', 'Arkansas', 'Republican', 'N00033363', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Dianne Feinstein', 'California', 'Democrat', 'N00007364', 1992);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Barbara Boxer', 'California', 'Democrat', 'N00006692', 1992);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Michael Bennet', 'Colorado', 'Democrat', 'N00030608', 2009);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Cory Gardner', 'Colorado', 'Republican', 'N00030780', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Richard Blumenthal', 'Connecticut', 'Democrat', 'N00031685', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Chris Murphy', 'Connecticut', 'Democrat', 'N00027566', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Tom Carper', 'Delaware', 'Democrat', 'N00012508', 2000);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Chris Coons', 'Delaware', 'Democrat', 'N00031820', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Bill Nelson', 'Florida', 'Democrat', 'N00009926', 2000);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Marco Rubio', 'Florida', 'Republican', 'N00030612', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Johnny Isakson', 'Georgia', 'Republican', 'N00002593', 2004);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('David Perdue', 'Georgia', 'Republican', 'N00035516', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Brian Schatz', 'Hawaii', 'Democrat', 'N00028138', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mazie Hirono', 'Hawaii', 'Democrat', 'N00028139', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mike Crapo', 'Idaho', 'Republican', 'N00006267', 1998);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jim Risch', 'Idaho', 'Republican', 'N00029441', 2008);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Dick Durbin', 'Illinois', 'Democrat', 'N00004981', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mark Kirk', 'Illinois', 'Republican', 'N00012539', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Dan Coats', 'Indiana', 'Republican', 'N00003845', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Joe Donnelly', 'Indiana', 'Democrat', 'N00026586', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Chuck Grassley', 'Iowa', 'Republican', 'N00001758', 1980);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Joni Ernst', 'Iowa', 'Republican', 'N00035483', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Pat Roberts', 'Kansas', 'Republican', 'N00005285', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jerry Moran', 'Kansas', 'Republican', 'N00005282', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mitch McConnell', 'Kentucky', 'Republican', 'N00003389', 1984);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Rand Paul', 'Kentucky', 'Republican', 'N00030836', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('David Vitter', 'Louisiana', 'Republican', 'N00009659', 2004);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Bill Cassidy', 'Louisiana', 'Republican', 'N00030245', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Susan Collins', 'Maine', 'Republican', 'N00000491', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Angus King', 'Maine', 'Independent', 'N00034580', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Barbara Mikulski', 'Maryland', 'Democrat', 'N00001945', 1986);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Ben Cardin', 'Maryland', 'Democrat', 'N00001955', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Elizabeth Warren', 'Massachusetts', 'Democrat', 'N00033492', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Ed Markey', 'Massachusetts', 'Democrat', 'N00000270', 2013);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Debbie Stabenow', 'Michigan', 'Democrat', 'N00004118', 2000);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Gary Peters', 'Michigan', 'Democrat', 'N00029277', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Amy Klobuchar', 'Minnesota', 'Democrat', 'N00027500', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Al Fraken', 'Minnesota', 'Democrat', 'N00029016', 2008);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Thad Cochran', 'Mississippi', 'Republican', 'N00003328', 1978);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Roger Wicker', 'Mississippi', 'Republican', 'N00003280', 2007);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Claire McCaskill', 'Missouri', 'Democrat', 'N00027694', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Roy Blunt', 'Missouri', 'Republican', 'N00005195', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jon Tester', 'Montana', 'Democrat', 'N00027605', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Steve Daines', 'Montana', 'Republican', 'N00033054', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Deb Fischer', 'Nebraska', 'Republican', 'N00033443', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Ben Sasse', 'Nebraska', 'Republican', 'N00035544', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Harry Reid', 'Nevada', 'Democrat', 'N00009922', 1986);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Dean Heller', 'Nevada', 'Republican', 'N00027522', 2011);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jeanne Shaheen', 'New Hampshire', 'Democrat', 'N00024790', 2008);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Kelly Ayotte', 'New Hampshire', 'Republican', 'N00030980', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Bob Menedez', 'New Jersey', 'Democrat', 'N00000699', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Cory Booker', 'New Jersey', 'Democrat', 'N00035267', 2013);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Tom Udall', 'New Mexico', 'Democrat', 'N00006561', 2008);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Martin Heinrich', 'New Mexico', 'Democrat', 'N00029835', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Chuck Schumer', 'New York', 'Democrat', 'N00001093', 1998);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Kirsten Gillibrand', 'New York', 'Democrat', 'N00027658', 2009);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Richard Burr', 'North Carolina', 'Republican', 'N00002221', 2004);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Thom Tillis', 'North Carolina', 'Republican', 'N00035492', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('John Hoeven', 'North Dakota', 'Republican', 'N00031688', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Heidi Heitkamp', 'North Dakota', 'Democrat', 'N00033782', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Sherrod Brown', 'Ohio', 'Democrat', 'N00003535', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Rob Portman', 'Ohio', 'Republican', 'N00003682', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jim Inhofe', 'Oklahoma', 'Republican', 'N00005582', 2004);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('James Lankford', 'Oklahoma', 'Republican', 'N00031129', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Ron Wyden', 'Oregon', 'Democrat', 'N00007724', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jeff Merkley', 'Oregon', 'Democrat', 'N00029303', 2008);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Bob Casey Jr.', 'Pennsylvania', 'Democrat', 'N00027503', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Pat Toomey', 'Pennsylvania', 'Republican', 'N00001489', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Jack Reed', 'Rhode Island', 'Democrat', 'N00000362', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Sheldon Whitehouse', 'Rhode Island', 'Democrat', 'N00027533', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Lindsey Graham', 'South Carolina', 'Republican', 'N00009975', 2002);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Tim Scott', 'South Carolina', 'Republican', 'N00031782', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('John Thune', 'South Dakota', 'Republican', 'N00004572', 2004);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mike  Rounds', 'South Dakota', 'Republican', 'N00035187', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Lamar Alexander', 'Tennessee', 'Republican', 'N00009888', 2002);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Bob Corker', 'Tennessee', 'Republican', 'N00027441', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('John Cornyn', 'Texas', 'Republican', 'N00024852', 2002);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Ted Cruz', 'Texas', 'Republican', 'N00033085', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Orrin Hatch', 'Utah', 'Republican', 'N00009869', 1976);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mike Lee', 'Utah', 'Republican', 'N00031696', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Patrick Leahy', 'Vermont', 'Democrat', 'N00009918', 1974);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Bernie Sanders', 'Vermont', 'Independent', 'N00000528', 2006);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mark Warner', 'Virginia', 'Democrat', 'N00002097', 2008);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Tim Kaine', 'Virginia', 'Democrat', 'N00033177', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Patty Murray', 'Washington', 'Democrat', 'N00007876', 1992);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Maria Cantwell', 'Washington', 'Democrat', 'N00007836', 2000);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Joe Manchin', 'West Virginia', 'Democrat', 'N00032838', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Shelly Moore Capito', 'West Virginia', 'Republican', 'N00009771', 2014);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Ron Johnson', 'Wisconsin', 'Republican', 'N00032546', 2010);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Tammy Baldwin', 'Wisconsin', 'Democrat', 'N00004367', 2012);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('Mike Enzi', 'Wyoming', 'Republican', 'N00006249', 1996);
INSERT INTO senators (name, state, party, api_id, year_elected) VALUES ('John Barrasso', 'Wyoming', 'Republican', 'N00006236', 2007);
